name: Deploy to FTP

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # версия Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # установка зависимостей

      - name: Install Sphinx
        run: |
          pip install sphinx  # Установка Sphinx

      - name: Build documentation
        run: |
          make html  # команда для генерации документации

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /techwriters.ru/test/  # путь на FTP-сервере
          local-dir: build/html/  # Путь к сгенерированным файлам
