name: Build site and Deploy to FTP

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Sphinx
        run: |
          pip install sphinx

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug PlantUML file
        run: |
          ls -l ./plantuml.jar
          file ./plantuml.jar

      - name: Set executable permission for plantuml.jar
        run: chmod +x ./plantuml.jar

      - name: Generate PlantUML diagrams
        id: generate_plantuml
        uses: grassedge/generate-plantuml-action@v1.5
        with:
          path: .  # Указывает на текущую директорию для поиска .rst файлов с диаграммами
          message: "Render PlantUML files"

      - name: Build documentation
        run: |
          make html

