name: CI/CD with Docker

on:
  push:
    branches:
      - develop  # Можно указать нужную вам ветку

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Используем Ubuntu для выполнения задач

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Шаг для клонирования репозитория

      - name: Build Docker
        run: |
          docker build -t my-docs-builder .
          docker run -d --name docs-builder my-docs-builder

      - name: Copy documentation artifacts
        run: |
          mkdir -p docs_artifacts
          docker cp docs-builder:/app/build/html docs_artifacts/

      - name: List documentation artifacts
        run: |
          ls -R docs_artifacts

      - name: Commit and push documentation artifacts
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs_artifacts
          git commit -m "Add documentation artifacts"
          git push origin ${{ github.ref }}


