name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker image
        run: |
          docker build -t techwritersweb .
          docker run -v $PWD:/app techwritersweb
      - name: Create temporary directory
        run: mkdir temp_html

      - name: Copy built documentation to temporary directory
        run: |
          if [ -d "/app/build/html" ] && [ -n "$(ls -A /app/build/html)" ]; then
            cp -r /app/build/html/* /app/temp_html/
          fi
      - name: List files in temp_html
        run: ls -A temp_html
