name: Deploy to FTP

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up FTP
        uses: wvbe/ftp-deploy-action@v2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/html  # Путь к вашим сгенерированным файлам
          remote-dir: /techwriters.ru  # Путь на FTP-сервере

