name: Build Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker image
        run: |
          docker build -t sphinx-docs .
          docker run -v $PWD/docs/_build/html:/app/source/_build/html sphinx-docs
