name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker image
        run: |
          docker build -t sphinx-docs .
          docker run -v $PWD/docs:/app/source sphinx-docs
          # Note: The above line mounts the entire 'docs' directory inside the container

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Upload to FTP server
        run: |
          lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R docs/_build/html /path/to/remote/directory"
        env:
          FTP_HOST: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
