name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: make build

      - name: Check documentation files
        run: |
          docker run -v $PWD/temp_html:/app/temp_html alpine ls -A /app/temp_html > temp_html_contents.txt

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: temp_html_contents
          path: temp_html_contents.txt
