name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t static-sphinx-site .

      - name: Copy artifacts from container
        run: docker cp $(docker ps -lq):/app/export - > ./artifacts.tar.gz

      - name: Upload artifacts to server
        run: scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./artifacts/* your_username@your_server:/path/to/destination/folder
