jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build and run Docker image
      run: |
        docker build -t techwritersweb .
        docker run -v $GITHUB_WORKSPACE:/app techwritersweb
        
    - name: List documentation files
      run: |
        ls $GITHUB_WORKSPACE/temp_html
