name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker image
        run: |
          docker build -t sphinx-docs .
          docker run -v $PWD/docs/_build/html:/app/source/_build/html sphinx-docs

      - name: Upload to FTP server
        uses: wvbe/ftp-action@v2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: docs/_build/html
          remoteDir: /
