
name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker image
        run: |
          docker build -t techwritersweb .
          docker run -v $PWD:/app techwritersweb

    - name: Check documentation files
      run: |
        if ls $GITHUB_WORKSPACE/temp_html/*.html 1> /dev/null 2>&1; then
          echo "Documentation files are present"
        else
          echo "No documentation files found"
          exit 1
        fi
