name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t techwritersweb .

      - name: Create temp dir
        run: mkdir -p $GITHUB_WORKSPACE/html

      - name: Copy built documentation from Docker image
        run: |
          CONTAINER_ID=$(docker create techwritersweb)
          docker cp $CONTAINER_ID:/app/temp_html $GITHUB_WORKSPACE/html
          docker rm $CONTAINER_ID

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Upload to FTP server
        run: |
          lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R $GITHUB_WORKSPACE/html /path/to/remote/directory"
        env:
          FTP_SERVER: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
